version: "3.8"
services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.betaaloverzichtapi.rule=HOST(`budget.timohermans.nl`)"
      - "traefik.http.services.betaaloverzichtapi.loadbalancer.server.port=80"

volumes:
  db-data:

networks:
  server:
    external: true